#!/bin/sh

#---------------------------------------
# Description
#---------------------------------------

# The Linux kernel can reset the system if serious problems are detected. 
# This can be implemented via special watchdog hardware (The Broadcom BCM2835 SoC on the Raspberry Pi comes with a hardware-based watchdog timer)
# Either way, there needs to be a daemon that tells the kernel the system is working fine. 
# If the daemon stops doing that, the system is reset.

#---------------------------------------
# Instructions
#---------------------------------------

# 1) Run this script. Watchdog.conf will open in the nano text editor.

# 2) Uncomment the line that starts with #watchdog-device by removing the hash (#) to enable the watchdog daemon to use the watchdog device.

# 3) Uncomment the line that says #max-load-1 = 24 by removing the hash symbol to reboot the device if the load goes over 24 over 1 minute. A load of 25 of one minute means that you would have needed 25 Raspberry Pis to complete that task in 1 minute. Tweak this value to your liking.

# 4) Reboot your Pi 3.

# 5) Optional: test the watchdog daemon.

#---------------------------------------
# Code
#---------------------------------------


# Load the watchdog kernel module
$ sudo modprobe bcm2708_wdog

# Load the module the next time the system boots, add a line to your /etc/modules file with "bcm2708_wdog".
$ echo "bcm2708_wdog" | sudo tee -a /etc/modules

#Make sure the watchdog daemon runs after every boot:
$ sudo chkconfig --add watchdog

#Configure the watchdog daemon - open /etc/watchdog.conf in nano
$ sudo nano /etc/watchdog.conf



